### ISSUE TITLE
service_platforms missing

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-vnv-curator#40]
ENV : Pre-int-bcn  

Test execution stop in curator

Payload {'event_actor': 'Curator', 'test_plan_uuid': '7374a3a8-701e-409d-abc7-793d0426c398', 'exception': '"service_platforms" field in test descriptor is required, found None', 'status': 'ERROR', 'test_results': []}

But my TD has this field

https://github.com/sonata-nfv/tng-tests/blob/master/packages/TSTINDP/Definitions/test-descriptor.yml

**Comment by juanlucruz** [comment]
@sinaure This Test Plan is not executing the one you are referring, but one created by tng-sdk-emulator

```
tng-cli -e http://pre-int-vnv-bcn.5gtango.eu test -g e6256a2f-84fe-45fb-9f13-3056a85bd69d

created_at: '2019-12-03T13:20:47.295+00:00'
executions: '0'
md5: 4c83ec8d39b570e2e3f2c5e083604b6f
pkg_ref: 1
signature: null
status: active
testd:
  author: tng-sdk-test
  description: Functional test for tng-smpilot-ns1-emulator
  descriptor_schema: https://raw.githubusercontent.com/sonata-nfv/tng-schema/master/test-descriptor/testdescriptor-schema.yml
  name: tng-sdk-test-tng-smpilot-ns1-emulator
  phases:
  - id: setup
    steps:
    - action: deploy
      description: Deploying a NS
      name: deployment
    - action: configure
      description: Configuring test
      name: configuration
      probes:
      - description: A container with tng-sdk-test and the test code
        id: tester
        image: registry.sonata-nfv.eu:5000/dummy
        name: tester
        parameters:
        - key: smpilot-cc_cdu04
          value: $(smpilot-cc/endpoints/name:cdu04/address)
        - key: smpilot-cc_cdu03
          value: $(smpilot-cc/endpoints/name:cdu03/address)
        - key: smpilot-cc_cdu02
          value: $(smpilot-cc/endpoints/name:cdu02/address)
        - key: smpilot-cc_cdu01
          value: $(smpilot-cc/endpoints/name:cdu01/address)
        - key: smpilot-eae_cdu01
          value: $(smpilot-eae/endpoints/name:cdu01/address)
  - id: excercise
    steps:
    - description: Run a probe with tng-sdk-test and the test code
      index: 0
      instances: 1
      name: run_tests
      output:
      - results: logs.txt
        verdict: status.txt
      run: tester
      start_delay: 0
  - id: verification
    steps:
    - condition:
      - condition: '='
        file: status.txt
        find: exit-code
        name: test-exit-code
        type: json
        value: '0'
        verdict: pass
      description: Check the exit-code of the test
      name: tester
      step: configure_service
  test_category:
  - functional
  testing_tags:
  - industrial-pilot-broker
  vendor: eu.5gtango
  version: '0.1'
updated_at: '2019-12-03T13:20:47.295+00:00'
username: ''
uuid: e6256a2f-84fe-45fb-9f13-3056a85bd69d
```

This test plan is launched probably due to the duplicity of testing tags specified in the package.
